### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by STESmly** [KiKi-XC/nonebot_plugin_logstream#1]
在使用nb plugin install nonebot-plugin-logstream安装之后报错10-07 09:33:20 [ERROR] nonebot | Failed to import "nonebot-plugin-logstream"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "E:\QQqunbot2\.venv\lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "E:\QQqunbot2\.venv\lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "E:\QQqunbot2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "E:\QQqunbot2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "E:\QQqunbot2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "D:\nonebot\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot-plugin-logstream'却能运行，然后在浏览器打开日志输出时报错10-07 09:31:35 [ERROR] uvicorn | Exception in ASGI application

Traceback (most recent call last):
  File "E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py", line 289, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py", line 278, in wrap
    await func()
  File "E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py", line 228, in listen_for_disconnect
    message = await receive()
  File "E:\QQqunbot2\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 555, in receive
    await self.message_event.wait()
  File "D:\nonebot\lib\asyncio\locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 1656922ca30

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "<string>", line 17, in <module>
  |   File "E:\QQqunbot2\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
  |     get_driver().run(*args, **kwargs)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
  |     uvicorn.run(
  |   File "E:\QQqunbot2\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
  |     server.run()
  |   File "E:\QQqunbot2\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
  |     return asyncio.run(self.serve(sockets=sockets))
  |   File "D:\nonebot\lib\asyncio\runners.py", line 44, in run
  |     return loop.run_until_complete(main)
  |   File "D:\nonebot\lib\asyncio\base_events.py", line 629, in run_until_complete
  |     self.run_forever()
  |   File "D:\nonebot\lib\asyncio\windows_events.py", line 321, in run_forever
  |     super().run_forever()
  |   File "D:\nonebot\lib\asyncio\base_events.py", line 596, in run_forever
  |     self._run_once()
  |   File "D:\nonebot\lib\asyncio\base_events.py", line 1890, in _run_once
  |     handle._run()
  |   File "D:\nonebot\lib\asyncio\events.py", line 80, in _run
  |     self._context.run(self._callback, *self._args)
  | > File "E:\QQqunbot2\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "E:\QQqunbot2\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
  |     return await self.app(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\applications.py", line 113, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
  |     raise exc
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
  |     await self.app(scope, receive, _send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
  |     raise exc
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\routing.py", line 715, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\routing.py", line 735, in app
  |     await route.handle(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\routing.py", line 288, in handle
  |     await self.app(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\routing.py", line 76, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
  |     raise exc
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\routing.py", line 74, in app
  |     await response(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py", line 289, in __call__
  |     await wrap(partial(self.listen_for_disconnect, receive))
  |   File "E:\QQqunbot2\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py", line 278, in wrap
    |     await func()
    |   File "E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py", line 258, in stream_response
    |     async for data in self.body_iterator:
    |   File "E:\QQqunbot2\.venv\lib\site-packages\nonebot_plugin_logstream\__init__.py", line 45, in log_generator
    |     log = await log_queue.get()
    |   File "D:\nonebot\lib\asyncio\queues.py", line 166, in get
    |     await getter
    | RuntimeError: Task <Task pending name='sse_starlette.sse.EventSourceResponse.__call__.<locals>.wrap' coro=<EventSourceResponse.__call__.<locals>.wrap() running at E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py:278> cb=[TaskGroup._spawn.<locals>.task_done() at E:\QQqunbot2\.venv\lib\site-packages\anyio\_backends\_asyncio.py:701]> got Future <Future pending> attached to a different loop
    +------------------------------------

**Comment by STESmly** [comment]
> 在使用nb plugin install nonebot-plugin-logstream安装之后报错10-07 09:33:20 [ERROR] nonebot | Failed to import "nonebot-plugin-logstream" Traceback (most recent call last): File "", line 14, in File "E:\QQqunbot2.venv\lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml return load_all_plugins(plugins, plugin_dirs) File "E:\QQqunbot2.venv\lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins return manager.load_all_plugins() File "E:\QQqunbot2.venv\lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins return set( File "E:\QQqunbot2.venv\lib\site-packages\nonebot\plugin\manager.py", line 204, in filter(None, (self.load_plugin(name) for name in self.available_plugins))
> 
> > File "E:\QQqunbot2.venv\lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
> > module = importlib.import_module(self._third_party_plugin_ids[name])
> > File "D:\nonebot\lib\importlib__init__.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1030, in _gcd_import
> > File "", line 1007, in _find_and_load
> > File "", line 984, in _find_and_load_unlocked
> > ModuleNotFoundError: No module named 'nonebot-plugin-logstream'却能运行，然后在浏览器打开日志输出时报错10-07 09:31:35 [ERROR] uvicorn | Exception in ASGI application
> 
> Traceback (most recent call last): File "E:\QQqunbot2.venv\lib\site-packages\sse_starlette\sse.py", line 289, in **call** await wrap(partial(self.listen_for_disconnect, receive)) File "E:\QQqunbot2.venv\lib\site-packages\sse_starlette\sse.py", line 278, in wrap await func() File "E:\QQqunbot2.venv\lib\site-packages\sse_starlette\sse.py", line 228, in listen_for_disconnect message = await receive() File "E:\QQqunbot2.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 555, in receive await self.message_event.wait() File "D:\nonebot\lib\asyncio\locks.py", line 226, in wait await fut asyncio.exceptions.CancelledError: Cancelled by cancel scope 1656922ca30
> 
> During handling of the above exception, another exception occurred:
> 
> * Exception Group Traceback (most recent call last):
>   |   File "", line 17, in 
>   |   File "E:\QQqunbot2.venv\lib\site-packages\nonebot__init__.py", line 335, in run
>   |     get_driver().run(*args, **kwargs)
>   |   File "E:\QQqunbot2.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
>   |     uvicorn.run(
>   |   File "E:\QQqunbot2.venv\lib\site-packages\uvicorn\main.py", line 577, in run
>   |     server.run()
>   |   File "E:\QQqunbot2.venv\lib\site-packages\uvicorn\server.py", line 65, in run
>   |     return asyncio.run(self.serve(sockets=sockets))
>   |   File "D:\nonebot\lib\asyncio\runners.py", line 44, in run
>   |     return loop.run_until_complete(main)
>   |   File "D:\nonebot\lib\asyncio\base_events.py", line 629, in run_until_complete
>   |     self.run_forever()
>   |   File "D:\nonebot\lib\asyncio\windows_events.py", line 321, in run_forever
>   |     super().run_forever()
>   |   File "D:\nonebot\lib\asyncio\base_events.py", line 596, in run_forever
>   |     self._run_once()
>   |   File "D:\nonebot\lib\asyncio\base_events.py", line 1890, in _run_once
>   |     handle._run()
>   |   File "D:\nonebot\lib\asyncio\events.py", line 80, in _run
>   |     self._context.run(self._callback, *self._args)
>   | > File "E:\QQqunbot2.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
>   |     result = await app(  # type: ignore[func-returns-value]
>   |   File "E:\QQqunbot2.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in **call**
>   |     return await self.app(scope, receive, send)
>   |   File "E:\QQqunbot2.venv\lib\site-packages\fastapi\applications.py", line 1054, in **call**
>   |     await super().**call**(scope, receive, send)
>   |   File "E:\QQqunbot2.venv\lib\site-packages\starlette\applications.py", line 113, in **call**
>   |     await self.middleware_stack(scope, receive, send)
>   |   File "E:\QQqunbot2.venv\lib\site-packages\starlette\middleware\errors.py", line 187, in **call**
>   |     raise exc
>   |   File "E:\QQqunbot2.venv\lib\site-packages\starlette\middleware\errors.py", line 165, in **call**
>   |     await self.app(scope, receive, _send)
>   |   File "E:\QQqunbot2.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in **call**
>   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
>   |   File "E:\QQqunbot2.venv\lib\site-packages\starlette_exception_handler.py", line 62, in wrapped_app
>   |     raise exc
>   |   File "E:\QQqunbot2.venv\lib\site-packages\starlette_exception_handler.py", line 51, in wrapped_app
>   |     await app(scope, receive, sender)
>   |   File "E:\QQqunbot2.venv\lib\site-packages\starlette\routing.py", line 715, in **call**
>   |     await self.middleware_stack(scope, receive, send)
>   |   File "E:\QQqunbot2.venv\lib\site-packages\starlette\routing.py", line 735, in app
>   |     await route.handle(scope, receive, send)
>   |   File "E:\QQqunbot2.venv\lib\site-packages\starlette\routing.py", line 288, in handle
>   |     await self.app(scope, receive, send)
>   |   File "E:\QQqunbot2.venv\lib\site-packages\starlette\routing.py", line 76, in app
>   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
>   |   File "E:\QQqunbot2.venv\lib\site-packages\starlette_exception_handler.py", line 62, in wrapped_app
>   |     raise exc
>   |   File "E:\QQqunbot2.venv\lib\site-packages\starlette_exception_handler.py", line 51, in wrapped_app
>   |     await app(scope, receive, sender)
>   |   File "E:\QQqunbot2.venv\lib\site-packages\starlette\routing.py", line 74, in app
>   |     await response(scope, receive, send)
>   |   File "E:\QQqunbot2.venv\lib\site-packages\sse_starlette\sse.py", line 289, in **call**
>   |     await wrap(partial(self.listen_for_disconnect, receive))
>   |   File "E:\QQqunbot2.venv\lib\site-packages\anyio_backends_asyncio.py", line 680, in **aexit**
>   |     raise BaseExceptionGroup(
>   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
>   +-+---------------- 1 ----------------
>   | Traceback (most recent call last):
>   |   File "E:\QQqunbot2.venv\lib\site-packages\sse_starlette\sse.py", line 278, in wrap
>   |     await func()
>   |   File "E:\QQqunbot2.venv\lib\site-packages\sse_starlette\sse.py", line 258, in stream_response
>   |     async for data in self.body_iterator:
>   |   File "E:\QQqunbot2.venv\lib\site-packages\nonebot_plugin_logstream__init__.py", line 45, in log_generator
>   |     log = await log_queue.get()
>   |   File "D:\nonebot\lib\asyncio\queues.py", line 166, in get
>   |     await getter
>   | RuntimeError: Task <Task pending name='sse_starlette.sse.EventSourceResponse.**call**..wrap' coro=<EventSourceResponse.**call**..wrap() running at E:\QQqunbot2.venv\lib\site-packages\sse_starlette\sse.py:278> cb=[TaskGroup._spawn..task_done() at E:\QQqunbot2.venv\lib\site-packages\anyio_backends_asyncio.py:701]> got Future  attached to a different loop
>   +------------------------------------

使用的v11+llob

**Comment by STESmly** [comment]
重新安装一次就没有启动报错，只有运行报错了

**Comment by KiKi-XC** [comment]
应该是pypi包有问题，你试试直接pull项目的[nonebot_plugin_logstream](https://github.com/KiKi-XC/nonebot_plugin_logstream/tree/main/nonebot_plugin_logstream)到你的nonebot插件目录下试试，并安装对应依赖

**Comment by STESmly** [comment]
> 应该是pypi包有问题，你试试直接pull项目的[nonebot_plugin_logstream](https://github.com/KiKi-XC/nonebot_plugin_logstream/tree/main/nonebot_plugin_logstream)到你的nonebot插件目录下试试，并安装对应依赖

我直接下载的项目源码压缩包，导入重载没问题，但一旦开始访问http://127.0.0.1:你的Nonebot端口/logs就开始反复报错10-13 19:11:15 [ERROR] uvicorn | Exception in ASGI application

Traceback (most recent call last):
  File "E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py", line 289, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py", line 278, in wrap
    await func()
  File "E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py", line 228, in listen_for_disconnect
    message = await receive()
  File "E:\QQqunbot2\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 555, in receive
    await self.message_event.wait()
  File "D:\nonebot\lib\asyncio\locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 21fafb185e0

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "<string>", line 17, in <module>
  |   File "E:\QQqunbot2\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
  |     get_driver().run(*args, **kwargs)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
  |     uvicorn.run(
  |   File "E:\QQqunbot2\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
  |     server.run()
  |   File "E:\QQqunbot2\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
  |     return asyncio.run(self.serve(sockets=sockets))
  |   File "D:\nonebot\lib\asyncio\runners.py", line 44, in run
  |     return loop.run_until_complete(main)
  |   File "D:\nonebot\lib\asyncio\base_events.py", line 629, in run_until_complete
  |     self.run_forever()
  |   File "D:\nonebot\lib\asyncio\windows_events.py", line 321, in run_forever
  |     super().run_forever()
  |   File "D:\nonebot\lib\asyncio\base_events.py", line 596, in run_forever
  |     self._run_once()
  |   File "D:\nonebot\lib\asyncio\base_events.py", line 1890, in _run_once
  |     handle._run()
  |   File "D:\nonebot\lib\asyncio\events.py", line 80, in _run
  |     self._context.run(self._callback, *self._args)
  | > File "E:\QQqunbot2\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "E:\QQqunbot2\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
  |     return await self.app(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\applications.py", line 113, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
  |     raise exc
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
  |     await self.app(scope, receive, _send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
  |     raise exc
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\routing.py", line 715, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\routing.py", line 735, in app
  |     await route.handle(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\routing.py", line 288, in handle
  |     await self.app(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\routing.py", line 76, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
  |     raise exc
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\starlette\routing.py", line 74, in app
  |     await response(scope, receive, send)
  |   File "E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py", line 289, in __call__
  |     await wrap(partial(self.listen_for_disconnect, receive))
  |   File "E:\QQqunbot2\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py", line 278, in wrap
    |     await func()
    |   File "E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py", line 258, in stream_response
    |     async for data in self.body_iterator:
    |   File "E:\QQqunbot2\src\plugins\log.py", line 45, in log_generator
    |     log = await log_queue.get()
    |   File "D:\nonebot\lib\asyncio\queues.py", line 166, in get
    |     await getter
    | RuntimeError: Task <Task pending name='sse_starlette.sse.EventSourceResponse.__call__.<locals>.wrap' coro=<EventSourceResponse.__call__.<locals>.wrap() running at E:\QQqunbot2\.venv\lib\site-packages\sse_starlette\sse.py:278> cb=[TaskGroup._spawn.<locals>.task_done() at E:\QQqunbot2\.venv\lib\site-packages\anyio\_backends\_asyncio.py:701]> got Future <Future pending> attached to a different loop
    +------------------------------------
